### ISSUE TITLE
[FEAT] Notify only on Fail/Warn

### ISSUE THREAD

**Issue by MonsterMuffin** [tigattack/VeeamNotify#11]
## Feat:

A configuration option to only send a notification when a job has failed or ended in a warning state.

Currently we have many jobs on many servers and it is sometimes difficult to spot failures even with notifications enabled. 

## Definition of done:

Only sending notifications on results other than success.

**Comment by tigattack** [comment]
Implemented in #22 and seems to be working. Let me know if you have any issues.
