### ISSUE TITLE
Error running the Installation Script

### ISSUE THREAD

**Issue by DevSkillsIT** [tigattack/VeeamNotify#26]
After running the script and entering the Slack URL we get the error below in powershell.
I tried with several options (B, F, N, W) and they all give the same error.

Exception setting "on_fail": "The property 'on_fail' cannot be found on this object. Verify that the property exists
and can be set."
At D:\Veeam\Scripts_Veeam\Installer.ps1:214 char:3
+         $config.mentions.on_fail = $true
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecord
![2022-04-12 12_42_01-172 16 1 6 - Conexão de Área de Trabalho Remota](https://user-images.githubusercontent.com/74376574/163001301-9f77bce5-7820-4985-addb-673b6b792879.png)
Exception
    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by tigattack** [comment]
I've transferred the issue as I believe it was created in the wrong repository (which I didn't notice at first!)

The fix should now be live on the dev branch.

**Comment by tigattack** [comment]
No response; closing.

Let me know if have any further issues.
