### ISSUE TITLE
[BUG] Config script ignores InstallParentPath

### ISSUE THREAD

**Issue by thespad** [tigattack/VeeamNotify#45]
### What happened?

If you allow the installer to configure your jobs for you it ignores any custom InstallParentPath and uses the default C:\VeeamScripts.

The install passes InstallParentPath here https://github.com/tigattack/VeeamNotify/blob/main/Installer.ps1#L390 but the DeployVeeamConfiguration.ps1 expects `$InstallPath` as a parameter

### Steps To Reproduce

* Run installer.ps1 with a custom InstallParentPath
* Allow the installer to configure jobs for you
* Check the post-job script path for the jobs

### VeeamNotify version

1.0-beta1

### PowerShell version

5.1

### Veeam Backup & Replication build number

11.0.1.1261

### Relevant log output

```PowerShell
.\VeeamNotify.ps1 -InstallParentPath "D:\VeeamScripts\" -Latest "Release"

Configuration set successfully. Configuration can be found in "D:\VeeamScripts\\VeeamNotify\config\conf.json".

Updated post-job script for job "Veeam esxi Backup".
Old: Powershell.exe -ExecutionPolicy Bypass -File D:\VeeamScripts\VeeamDiscordNotifications\DiscordNotificationBootstrap.ps1
New: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\VeeamScripts\VeeamNotify\Bootstrap.ps1
```
```

**Comment by thespad** [comment]
Looks good to me.

**Comment by tigattack** [comment]
Awesome, cheers!
