### ISSUE TITLE
[BUG] installer is broken due

### ISSUE THREAD

**Issue by s0yun** [tigattack/VeeamNotify#58]
### What happened?

When attempting to run the installer in either option 1 or 2 it's checking for a file but the file doesn't exisit because the installer hasn't downloaded any of the applications file yet. 

![Screenshot 2023-08-20 at 14 05 01](https://github.com/tigattack/VeeamNotify/assets/77540086/cb58442c-36e1-4dfd-89d1-330e8dcaf5d6)

As I understand the installer in it's present iteration it should automatically download the needed files?

### Steps To Reproduce

Run either option 1  or option 2 for installer on a veeam instance that's not got veeamnotify currently setup. 

### VeeamNotify version

v1.0

### PowerShell version

5.1

### Veeam Backup & Replication build number

11.0.0.837

### Relevant log output

```PowerShell
Unable to provide any logs as the installer fails,
```

**Comment by tigattack** [comment]
Thanks for the report. Looks like I made a poor assumption that if the install path exists, so will `resources\version.txt`.

Unrelated, but FYI it seems like you manually typed the install line in the first command, hence the error there.

I've pushed a fix, please retry like so and let me know how it goes:

```ps
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/tigattack/VeeamNotify/58-bug-installer-is-broken-due-1/Installer.ps1'))
```

**Comment by s0yun** [comment]
Worked after two tries, installer crashed on running config deployment script.
