### ISSUE TITLE
[BUG] No creating log file or sending notification to Teams Hook

### ISSUE THREAD

**Issue by cantercrow** [tigattack/VeeamNotify#60]
### What happened?

OS: Windows Server 2016
Veeam: version 12 latest 

I ran the command below and ran through the setup with no issues and checked in Veeam and can see the scripts have been added but when I have a failed backup nothing appears in Teams.

I have created a webhook in Teams and confirmed the information is correct.

I have enabled the debug logging in the config file but the log folder is empty and no logs created.

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/tigattack/VeeamNotify/main/Installer.ps1'))

### Steps To Reproduce

1. Ran backup and did a stop job, job showed failed.
2. No information was posted to the Teams Channel.
3. no logs files were generated even with debug enabled.

### VeeamNotify version

v1.0

### PowerShell version

5.1

### Veeam Backup & Replication build number

12.0.0.1420 P20230412

### Relevant log output

```PowerShell
{
    "services":  {
                     "discord":  {
                                     "webhook":  "DiscordWebhook",
                                     "user_id":  "123456789"
                                 },
                     "slack":  {
                                   "webhook":  "SlackWebhook",
                                   "user_id":  "A1B2C3D4E5"
                               },
                     "teams":  {
                                   "webhook":  "https://ttmcazurettmcco.webhook.office.com/webhookb2/b688e623removed",
                                   "user_id":  "removed@uk.teams.ms",
                                   "user_name":  ""
                               }
                 },
    "mentions":  {
                     "on_failure":  true,
                     "on_warning":  true
                 },
    "notifications":  {
                          "on_success":  true,
                          "on_failure":  true,
                          "on_warning":  true
                      },
    "logging":  {
                    "enabled":  true,
                    "level":  "debug",
                    "max_age_days":  7
                },
    "update":  {
                   "notify":  true,
                   "auto_update":  false,
                   "auto_update_comment":  "auto_update will NOT work. Leave as \u0027false\u0027"
               },
    "thumbnail":  "https://raw.githubusercontent.com/tigattack/VeeamDiscordNotifications/master/asset/thumb01.png"
}
```

**Comment by cantercrow** [comment]
It appears to have started to work without changing anything.

**Comment by tigattack** [comment]
Glad to hear the issue's resolved, thanks for the update!
