### ISSUE TITLE
[BUG] � instead of umlauts

### ISSUE THREAD

**Issue by mx4k** [tigattack/VeeamNotify#72]
### What happened?

I'm using VeeamNotify on a German server. The date contains umlauts and the current encoding doesn't seem to support them.

![grafik](https://github.com/tigattack/VeeamNotify/assets/8719632/1f36e3e4-f96f-4a77-99cf-6b9491c10b84)

### Steps To Reproduce

1. run script in german enviroment

### VeeamNotify version

v1.0

### PowerShell version

5.1

**Comment by mx4k** [comment]
Hi @tigattack, thanks for your quick reply. Sure, I'm happy to help to improve your already great project.

**Comment by tigattack** [comment]
Great, cheers.

File: resources/NotificationHandler.psm1
Line: 283
Original line: `text     = "$((Get-Date -UFormat '%d %B %Y %R').ToString())"`
New line: `text     = [System.Web.HttpUtility]::HtmlEncode((Get-Date -UFormat '%d %B %Y %R').ToString())`

**Comment by mx4k** [comment]
@tigattack unfortunately, it didn't do the trick.

![grafik](https://github.com/tigattack/VeeamNotify/assets/8719632/17b3bb89-1482-4e48-a752-2e3947cb38bb)

**Comment by tigattack** [comment]
That's my bad, I missed the broken characters in the lower fields, only saw the one in the date at the top. It's proven my theory though, as that one is now fixed. Thanks for the help! I'll get a fix out ASAP.
