### ISSUE TITLE
job status Api callback

### ISSUE THREAD

**Issue by AmirAghaee** [tigattack/VeeamNotify#77]
### Is your feature request related to a problem?

Hello,

I am planning to create an admin dashboard to manage and monitor job status in Veeam. I would like to display job progress as a percentage on this dashboard.

To do this effectively, I need to set up callbacks from Veeam to fetch relevant data. Unfortunately, I couldn't find any documentation on this process.

Does your package support sending information to a specific URL for this purpose?

Thank you for your assistance.

**Comment by tigattack** [comment]
This sounds cool. Unfortunately VeeamNotify doesn't support that sort of functionality, and is only triggered upon job completion anyway.
