### ISSUE TITLE
[FEAT] New service: write a personalized custom atribute on Vsphere

### ISSUE THREAD

**Issue by iacobus1977** [tigattack/VeeamNotify#83]
### Is your feature request related to a problem?

No

**Comment by tigattack** [comment]
I'd consider this to be out of scope for this project, sorry. For those who want this, I'd recommend writing your own script to do so. From a quick search, it looks [pretty straight forward](https://angrysysops.com/2023/03/23/create-and-assign-a-custom-attribute-for-virtual-machines-in-vcenter-using-powershell)! :)

To have this run at the end of a job like VeeamNotify, you'd need a wrapper script to launch both your custom attribute script and VeeamNotify. I'd recommend reviewing [Bootstrap.ps1](https://github.com/tigattack/VeeamNotify/blob/main/Bootstrap.ps1) to get an idea of how this would work.
